# Generated by Django 5.2.6 on 2025-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='llm_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
