# Generated by Django 5.2.6 on 2025-11-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_llm_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='detailed_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
